// Snapshot of the most common disposable e-mail domains.
// MAJ trimestrielle manuelle (cf spec, Hors périmètre V1: auto-MAJ).
// Source de réf: github.com/disposable-email-domains/disposable-email-domains
// Stocké en Set lowercase pour lookup O(1).

const DOMAINS: readonly string[] = [
  "0-mail.com","027168.com","0815.ru","0clickemail.com","0wnd.net","0wnd.org",
  "10minutemail.co.uk","10minutemail.com","10minutemail.de","10minutemail.net",
  "1secmail.com","1secmail.net","1secmail.org",
  "20minutemail.com","2prong.com","30minutemail.com","33mail.com","3d-painting.com",
  "4warding.com","4warding.net","4warding.org",
  "anonbox.net","anonymbox.com","antichef.com","antichef.net","antispam.de","antispammail.de",
  "binkmail.com","bobmail.info","bofthew.com","bouncr.com","breakthru.com","brefmail.com",
  "byom.de",
  "chacuo.net","chammy.info","cool.fr.nf","correo.blogos.net","cosmorph.com","courriel.fr.nf",
  "courrieltemporaire.com","crapmail.org","cust.in","cuvox.de",
  "dacoolest.com","dandikmail.com","dayrep.com","deadaddress.com","deagot.com","despam.it",
  "devnullmail.com","dfgh.net","digitalsanctuary.com","disposableaddress.com","disposablemail.com",
  "disposeamail.com","disposemail.com","dispostable.com","dodgeit.com","dodgit.com","dodgit.org",
  "dogit.com","donemail.ru","dontreg.com","dontsendmespam.de","drdrb.net",
  "easytrashmail.com","einrot.com","email60.com","emailgo.de","emailias.com","emailinfive.com",
  "emaillox.com","emailmiser.com","emailproxsy.com","emailsensei.com","emailtemporario.com.br",
  "emailto.de","emailwarden.com","emailx.at.hm","emailxfer.com","emeil.in","emeil.ir",
  "emz.net","ero-tube.org","etranquil.com","etranquil.net","etranquil.org","explodemail.com",
  "fakeinbox.com","fakeinformation.com","fastacura.com","fastchevy.com","fastchrysler.com",
  "fastkawasaki.com","fastmazda.com","fastmitsubishi.com","fastnissan.com","fastsubaru.com",
  "fastsuzuki.com","fasttoyota.com","fastyamaha.com","filzmail.com","fixmail.tk","fizmail.com",
  "fr33mail.info","frapmail.com","front14.org","fuckingduh.com",
  "garliclife.com","get1mail.com","get2mail.fr","getairmail.com","getmails.eu","getonemail.com",
  "ghosttexter.de","girlsundertheinfluence.com","gishpuppy.com","goemailgo.com","gotmail.net",
  "gotmail.org","gotti.otherinbox.com","great-host.in","greensloth.com","grr.la","gsrv.co.uk",
  "guerillamail.biz","guerillamail.com","guerillamail.de","guerillamail.info","guerillamail.net",
  "guerillamail.org","guerillamailblock.com","guerrillamail.biz","guerrillamail.com",
  "guerrillamail.de","guerrillamail.info","guerrillamail.net","guerrillamail.org","guerrillamailblock.com",
  "haltospam.com","harakirimail.com","hidemail.de","hidzz.com","hmamail.com","hopemail.biz",
  "ieh-mail.de","ikbenspamvrij.nl","imails.info","inboxalias.com","inboxclean.com","inboxclean.org",
  "incognitomail.com","incognitomail.net","incognitomail.org","insorg-mail.info","ip6.li",
  "ipoo.org","irish2me.com","iwi.net",
  "jetable.com","jetable.fr.nf","jetable.net","jetable.org","jnxjn.com","jourrapide.com",
  "kasmail.com","keepmymail.com","killmail.com","killmail.net","kir.ch.tc","klassmaster.com",
  "klzlk.com","koszmail.pl","kurzepost.de",
  "lawlita.com","letthemeatspam.com","lhsdv.com","lifebyfood.com","link2mail.net",
  "linuxmail.so","litedrop.com","lol.ovpn.to","lookugly.com","lortemail.dk","lr78.com","lroid.com",
  "lukop.dk",
  "m21.cc","maboard.com","mail-temporaire.fr","mail.by","mail.mezimages.net","mail.zp.ua",
  "mail1a.de","mail2rss.org","mail333.com","mail4trash.com","mailbidon.com","mailbiz.biz",
  "mailblocks.com","mailbucket.org","mailcat.biz","mailcatch.com","maildrop.cc","mailexpire.com",
  "mailfa.tk","mailforspam.com","mailfreeway.com","mailguard.me","mailhz.me","mailimate.com",
  "mailin8r.com","mailinator.com","mailinater.com","mailinator.net","mailinator2.com",
  "mailinator2.net","mailincubator.com","mailismagic.com","mailme.lv","mailme24.com",
  "mailmetrash.com","mailmoat.com","mailms.com","mailnesia.com","mailnull.com","mailorg.org",
  "mailpick.biz","mailrock.biz","mailscrap.com","mailshell.com","mailsiphon.com","mailtothis.com",
  "mailtrash.net","mailtv.net","mailtv.tv","mailzilla.com","mailzilla.org","makemetheking.com",
  "manybrain.com","mbx.cc","mega.zik.dj","meinspamschutz.de","meltmail.com","messagebeamer.de",
  "mintemail.com","misterpinball.de","moncourrier.fr.nf","monemail.fr.nf","monmail.fr.nf",
  "msa.minsmail.com","mt2009.com","mt2014.com","mycard.net.ua","mycleaninbox.net",
  "mymailoasis.com","mypartyclip.de","myphantomemail.com","mysamp.de","mytempemail.com",
  "mytempmail.com","mytrashmail.com",
  "nabuma.com","neomailbox.com","nepwk.com","nervmich.net","nervtmich.net","netmails.com",
  "netmails.net","neverbox.com","no-spam.ws","nobulk.com","noclickemail.com","nogmailspam.info",
  "nomail.xl.cx","nomail2me.com","nomorespamemails.com","nospam.ze.tc","nospam4.us","nospamfor.us",
  "nospammail.net","notmailinator.com","nowhere.org","nowmymail.com","nurfuerspam.de",
  "objectmail.com","obobbo.com","odnorazovoe.ru","oneoffemail.com","onewaymail.com",
  "online.ms","oopi.org","ordinaryamerican.net","otherinbox.com","ourklips.com",
  "outlawspam.com","ovpn.to","owlpic.com",
  "pancakemail.com","pjjkp.com","plexolan.de","poczta.onet.pl","politikerclub.de","poofy.org",
  "pookmail.com","privacy.net","privatdemail.net","proxymail.eu","prtnx.com","punkass.com",
  "putthisinyourspamdatabase.com","pwrby.com",
  "quickinbox.com",
  "rcpt.at","reallymymail.com","recode.me","recursor.net","reliable-mail.com","rhyta.com",
  "rmqkr.net","royal.net","rppkn.com","rtrtr.com","s0ny.net","safe-mail.net","safersignup.de",
  "safetymail.info","safetypost.de","sandelf.de","saynotospams.com","schafmail.de","schrott-email.de",
  "secretemail.de","secure-mail.biz","selfdestructingmail.com","sendspamhere.com","sharedmailbox.org",
  "sharklasers.com","shieldedmail.com","shieldemail.com","shiftmail.com","shitmail.me","shitmail.org",
  "shitware.nl","shmeriously.com","shortmail.net","sibmail.com","skeefmail.com","slapsfromlastnight.com",
  "slaskpost.se","smashmail.de","smellfear.com","snakemail.com","sneakemail.com","sneakmail.de",
  "snkmail.com","sofimail.com","sofort-mail.de","softpls.asia","sogetthis.com","soodonims.com",
  "spam.la","spam.su","spam4.me","spamavert.com","spambob.com","spambob.net","spambob.org",
  "spambog.com","spambog.de","spambog.net","spambog.ru","spambox.info","spambox.org","spambox.us",
  "spamcannon.com","spamcannon.net","spamcero.com","spamcorptastic.com","spamcowboy.com",
  "spamcowboy.net","spamcowboy.org","spamday.com","spamex.com","spamfree.eu","spamfree24.com",
  "spamfree24.de","spamfree24.eu","spamfree24.info","spamfree24.net","spamfree24.org","spamgoes.in",
  "spamgourmet.com","spamgourmet.net","spamgourmet.org","spamherelots.com","spamhereplease.com",
  "spamhole.com","spamify.com","spaml.com","spaml.de","spammotel.com","spamobox.com","spamoff.de",
  "spamslicer.com","spamspot.com","spamthis.co.uk","spamthisplease.com","spamtrail.com",
  "spamtroll.net","speed.1s.fr","supergreatmail.com","supermailer.jp","superrito.com",
  "superstachel.de","suremail.info","svk.jp",
  "tafmail.com","tagyourself.com","talkinator.com","tapchicongnghe.net","teewars.org",
  "teleworm.com","teleworm.us","temp-mail.com","temp-mail.org","temp-mail.ru","tempail.com",
  "tempemail.biz","tempemail.com","tempinbox.co.uk","tempinbox.com","tempmail.eu","tempmaildemand.com",
  "tempmailer.com","tempmailer.de","tempomail.fr","temporarily.de","temporarioemail.com.br",
  "temporaryemail.net","temporaryforwarding.com","temporaryinbox.com","temporarymailaddress.com",
  "tempymail.com","thanksnospam.info","thankyou2010.com","thc.st","thelimestones.com","thismail.net",
  "throwawayemailaddress.com","throwawaymail.com","tilien.com","tittbit.in","tizi.com","tmail.ws",
  "tmailinator.com","toomail.biz","topranklist.de","tradermail.info","trash-mail.at","trash-mail.com",
  "trash-mail.de","trash2009.com","trashdevil.com","trashemail.de","trashinbox.com","trashmail.at",
  "trashmail.com","trashmail.de","trashmail.me","trashmail.net","trashmail.org","trashmail.ws",
  "trashmailer.com","trashymail.com","trashymail.net","trbvm.com","trialmail.de","trillianpro.com",
  "twinmail.de","tyldd.com",
  "uggsrock.com","umail.net","upliftnow.com","uplipht.com","uroid.com","us.af","venompen.com",
  "veryrealemail.com","viditag.com","viralplays.com","vpn.st","vsimcard.com","vubby.com",
  "wasteland.rfc822.org","webemail.me","weg-werf-email.de","wegwerf-emails.de","wegwerfadresse.de",
  "wegwerfemail.com","wegwerfemail.de","wegwerfmail.de","wegwerfmail.info","wegwerfmail.net",
  "wegwerfmail.org","wh4f.org","whatpaas.com","whatiaas.com","whyspam.me","willhackforfood.biz",
  "willselfdestruct.com","winemaven.info","wronghead.com","wuzup.net","wuzupmail.net",
  "www.e4ward.com","www.gishpuppy.com","www.mailinator.com","wwwnew.eu",
  "x.ip6.li","xagloo.com","xemaps.com","xents.com","xmaily.com","xoxy.net","yep.it",
  "yogamaven.com","yopmail.com","yopmail.fr","yopmail.net","yourdomain.com","ypmail.webarnak.fr.eu.org",
  "yuurok.com","z1p.biz","za.com","zehnminuten.de","zehnminutenmail.de","zetmail.com",
  "zippymail.info","zoaxe.com","zoemail.org",
];

export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set(DOMAINS.map((d) => d.toLowerCase()));

export function isDisposable(domain: string): boolean {
  return DISPOSABLE_DOMAINS.has(domain.trim().toLowerCase());
}
